### ISSUE TITLE
Not notifying new issues

### ISSUE THREAD

**Issue by josemaX** [mantisbt-plugins/TelegramBot#22]
I've this working on Mantis 2.18 (later will upgrade to 2.19) and it doesn't notify me (admin) new issues, but it notifies when users add new comments.

Is this a known problem or I'm missing some config/adjustment?

Thanks!

**Comment by brlumen** [comment]
@josemaX Hello! 
Please provide settings on the page.: plugin.php?page=TelegramBot/account_telegram_prefs_page

**Comment by josemaX** [comment]
Sure, attached a capture
<img width="1173" alt="telegram settings" src="https://user-images.githubusercontent.com/424840/52632686-8156e700-2ec2-11e9-857f-cb4cfe38c43d.png">

**Comment by josemaX** [comment]
The settings text (at left) are blanked any language I choose, I was working in spanish but changed to english for screenshot. As I have everything checked and selected "Any" i think this would be fine.

**Comment by brlumen** [comment]
@josemaX Thanks for the bug report.
Indeed, there were errors in the localization files, I fixed them. Spanish should now work fine.

Please download this fixed version of the plugin:
https://github.com/brlumen/TelegramBot/archive/issue_22.zip

If after installing the corrected version, the messages will not come - we will find out further.
At the moment I have tested sending messages to an administrative account. I did not notice the errors.
