### ISSUE TITLE
Support for version 2.18.0

### ISSUE THREAD

**Issue by cedrickzepp** [mantisbt-plugins/TelegramBot#24]
Support for version 2.18.0
I installed the file TelegramBot-release-1.4.0 but, regrettably, it is not compatible with version 2.18.0, help, please!

Best regards...

**Comment by brlumen** [comment]
@cedrickzepp Hello! Plugin compatible with 2.18.0.
Tell me more about what does not work for you?

**Comment by brlumen** [comment]
@cedrickzepp 
I am preparing a new release in which some bugs were fixed. Maybe he will help you.
Download the pre-build link:
https://github.com/brlumen/TelegramBot/archive/issue_22.zip

**Comment by cedrickzepp** [comment]
I have copied the contents of the .zip file into the mantisbt / plugins folder, however, it is not seen in the plugins administration page.
![screenshot 2019-02-18 at 12 43 42](https://user-images.githubusercontent.com/47735589/52970828-e440f600-337a-11e9-901d-40878dfc2e8b.png)
![screenshot 2019-02-18 at 12 43 24](https://user-images.githubusercontent.com/47735589/52970829-e440f600-337a-11e9-9845-8a882b4f4283.png)
![screenshot 2019-02-18 at 12 43 07](https://user-images.githubusercontent.com/47735589/52970830-e440f600-337a-11e9-87c0-b81e1acbb0c4.png)

**Comment by brlumen** [comment]
@cedrickzepp 
The folder name must match the name of the plug-in, a letter per letter, without version information, etc.
When I first started using mantisbts, I also had a long time to deal with the fact that the plugins did not work.
Rename the folder to TelegramBot. 
Make sure that TelegramBot.php is in the root of the folder.
