### ISSUE TITLE
Unable to select Project

### ISSUE THREAD

**Issue by intervisionlord** [mantisbt-plugins/TelegramBot#26]
I have 3 projects. When sending a message to the bot, he offers to start a task or add a comment, but does not offer to select a project. The first created project is always selected.

**Comment by brlumen** [comment]
@intervisionlord Hi!
This happens because you have selected a specific project in your user settings. Set the default project "All projects" and then the bot will offer to choose a project from the list.

**Comment by intervisionlord** [comment]
yep, it helps. Thanks.
