### ISSUE TITLE
Unable to use in mantis 2.24.1

### ISSUE THREAD

**Issue by dslima90** [mantisbt-plugins/TelegramBot#32]
I'm getting:

INTERNAL APPLICATION ERROR

When enter in the configuration page.

I tried to use:

```
$g_display_errors = array (
   E_ALL => DISPLAY_ERROR_INLINE,
  );
```

But the same message appears.

I am using mantis 2.24.1, is this version compatible?

Screenshots folow:

![configuration page](https://user-images.githubusercontent.com/11665048/81695893-9e69c500-9439-11ea-9aa1-6a61b4eb0ebd.png)

![Screenshot from 2020-05-12 10-14-53](https://user-images.githubusercontent.com/11665048/81695920-a6c20000-9439-11ea-8ce3-f9e9857975fc.png)

**Comment by brlumen** [comment]
Please provide more information about the system. Version: php, DB, OS, curl.
Also make sure that there are no errors related to the plugin in the mantisbt logs. If so, provide them.

**Comment by dslima90** [comment]
I am using PHP7 on ubuntu server 18.04 and mysql. Serving with Apache.

Using:

```
$g_log_level = LOG_PLUGIN;
$g_log_destination         = 'file:/srv/mantisbt/mantisbt.log';
```

There is no logs available.

![Screenshot from 2020-05-13 07-38-58](https://user-images.githubusercontent.com/11665048/81802686-e8f84980-94ec-11ea-8845-856c7f2a5ecf.png)

**Comment by brlumen** [comment]
I am unable to reproduce the problem.
If the question is still relevant, then enable LOG_ALL and send the logs.
I also recommend updating mantisbt to the latest version.

**Comment by brlumen** [comment]
You may have a strict error handling mode. The current version of the bot uses obsolete functions of the matnisbt core. I will be releasing an update shortly to fix this bug, but for now you can disable strict mode. Refer to the help for the '$g_display_errors' variable in the mantisbt config file.

**Comment by doker445** [comment]
Hello!
Have the same issue. After upgrade mantis to 2.24.4 begun get error INTERNAL APPLICATION ERROR after add comment.
In logs I see:
`[Tue Jan 05 13:54:22.588266 2021] [php:notice] [pid 11804] [client 128.0.170.69:19635] Unknown named parameter $files\n/var/www/mantisbt-2.24.4/core/event_api.php: 232: - - - - event_callback( <string>'EVENT_BUGNOTE_ADD', <string>'telegram_message_bugnote_add', <string>'TelegramBot', <array> { [0] => 60029, [1] => 243064, ['files'] => <array> {  } } )\n/var/www/mantisbt-2.24.4/core/event_api.php: 164: - - - - event_type_execute( <string>'EVENT_BUGNOTE_ADD', <array> { ['TelegramBot'] => <array> { [0] => 'telegram_message_bugnote_add' } }, <array> { [0] => 60029, [1] => 243064, ['files'] => <array> {  } } )\n/var/www/mantisbt-2.24.4/core/commands/IssueNoteAddCommand.php: 281: - - - - event_signal( <string>'EVENT_BUGNOTE_ADD', <array> { [0] => 60029, [1] => 243064, ['files'] => <array> {  } } )\n/var/www/mantisbt-2.24.4/core/commands/Command.php: 137: IssueNoteAddCommand - -> - process()\n/var/www/mantisbt-2.24.4/bugnote_add.php: 64: Command - -> - execute()\n`

**Comment by doker445** [comment]
TelegramBot plugins works with php8.0 ?
