### ISSUE TITLE
Cant activate the plugin - trying to connect to telegram

### ISSUE THREAD

**Issue by fstltna** [mantisbt-plugins/TelegramBot#36]
Trying to connect up telegram like this:
![telegram_01](https://user-images.githubusercontent.com/883076/184336851-e5109b53-6a0d-4708-a266-6ded262a357c.png)
I get this error:
![RepoSetup04](https://user-images.githubusercontent.com/883076/184336463-77d72af8-cd80-4ef0-bdc7-461024ecb3f8.png)
:

Any ideas on what I have to do?

**Comment by brlumen** [comment]
Please describe your configuration.


пт, 12 авг. 2022 г., 17:32 Marisa Giancarla ***@***.***>:

**Comment by fstltna** [comment]
Ubuntu 20.04 with latest MantisBT (2.25.5 I believe) and latest telegram plugin. What other do you need?

**Comment by brlumen** [comment]
Database version. Database provider.

пт, 12 авг. 2022 г., 18:34 Marisa Giancarla ***@***.***>:

**Comment by fstltna** [comment]
![bug_database](https://user-images.githubusercontent.com/883076/184535573-19d0985d-f446-4aa1-95b2-2a7882ac6386.png)

**Comment by josemaX** [comment]
> Trying to connect up telegram like this: ![telegram_01](https://user-images.githubusercontent.com/883076/184336851-e5109b53-6a0d-4708-a266-6ded262a357c.png) I get this error: ![RepoSetup04](https://user-images.githubusercontent.com/883076/184336463-77d72af8-cd80-4ef0-bdc7-461024ecb3f8.png) :
> 
> Any ideas on what I have to do?

It seems your telegram ID is too large for the database field type. Are you sure that is your user ID? (I don't think Telegram has 5 billion users) I think they were about 700 millions months ago.

**Comment by josemaX** [comment]
I see the ID has nothing to see in number of user as I have one 7xx million from several years ago.

Then, the problem seems to be (if ID is correct) it doesn't fit in an INTEGER Column in MySQL: (C&P)

_"The signed range of INT is from -2147483648 to 2147483647 **and the unsigned range is from 0 to 4294967295**. You can specify signed or unsigned int in the column definition"_

**Comment by brlumen** [comment]
And there is. I need some time to release a patch.
